<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\TradingStructures.Common\TradingStructures.Common.csproj" />
        <ProjectReference Include="..\TradingStructures.Exchanges.Interfaces\TradingStructures.Exchanges.Interfaces.csproj" />
        <ProjectReference Include="..\TradingStructures.OrderManagement.Interfaces\TradingStructures.OrderManagement.Interfaces.csproj" />
        <ProjectReference Include="..\TradingStructures.MarketData.Interfaces\TradingStructures.MarketData.Interfaces.csproj" />
        <ProjectReference Include="..\TradingStructures.Strategies.Interfaces\TradingStructures.Strategies.Interfaces.csproj" />
    </ItemGroup>

    <ItemGroup Condition="!$(MSBuildProjectFile.Contains('.Tests'))">
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Effanville.TradingConsole.Tests</_Parameter1>
        </AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
		<_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
	</AssemblyAttribute>
	</ItemGroup>

</Project>
