<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Nager.Date" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FinancialStructures\Common\src\Common.Console\Common.Console.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\src\FinancialStructures\FinancialStructures.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\src\FinancialStructures.Stocks\FinancialStructures.Stocks.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\Common\src\Common.Structure\Common.Structure.csproj" />
    <ProjectReference Include="..\TradingStructures.Common\TradingStructures.Common.csproj" />
    <ProjectReference Include="..\TradingStructures.Exchanges\TradingStructures.Exchanges.csproj" />
    <ProjectReference Include="..\TradingStructures.Exchanges.Interfaces\TradingStructures.Exchanges.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.MarketData.Interfaces\TradingStructures.MarketData.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.MarketData\TradingStructures.MarketData.csproj" />
    <ProjectReference Include="..\TradingStructures.OrderManagement.Interfaces\TradingStructures.OrderManagement.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.OrderManagement\TradingStructures.OrderManagement.csproj" />
    <ProjectReference Include="..\TradingStructures.StaticData.Interfaces\TradingStructures.StaticData.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.StaticData\TradingStructures.StaticData.csproj" />
    <ProjectReference Include="..\TradingStructures.StockMarket.Interfaces\TradingStructures.StockMarket.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.StockMarket\TradingStructures.StockMarket.csproj" />
    <ProjectReference Include="..\TradingStructures.Strategies.Interfaces\TradingStructures.Strategies.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.Strategies\TradingStructures.Strategies.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Effanville.TradingConsole.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
