<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <None Update="ExampleFiles\example-configure-file.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="ExampleFiles\example-database-empty.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="ExampleFiles\example-database.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="ExampleFiles\small-exchange-empty.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="ExampleFiles\small-exchange.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="ExampleFiles\small-exchange.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
