<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nager.Date" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingSystem\TradingSystem.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\src\FinancialStructures\FinancialStructures.csproj" />
      <ProjectReference Include="..\..\FinancialStructures\src\FinancialStructures.Stocks\FinancialStructures.Stocks.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\Common\src\Common.Structure\Common.Structure.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\Common\src\Common.Console\Common.Console.csproj" />
  </ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>TradingConsole.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
