<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <ProjectReference Include="..\TradingStructures.OrderManagement.Interfaces\TradingStructures.OrderManagement.Interfaces.csproj" />
    <ProjectReference Include="..\TradingStructures.StockMarket.Interfaces\TradingStructures.StockMarket.Interfaces.csproj" />
  </ItemGroup>

</Project>