<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
      <ProjectReference Include="..\TradingStructures.Common\TradingStructures.Common.csproj" />
      <ProjectReference Include="..\TradingStructures.MarketData.Interfaces\TradingStructures.MarketData.Interfaces.csproj" />
    </ItemGroup>

</Project>
