<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Nager.Date" />
        <PackageReference Include="System.IO.Abstractions" />
        <PackageReference Include="System.Net.Http" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\FinancialStructures\Common\src\Common.Structure\Common.Structure.csproj" />
      <ProjectReference Include="..\..\FinancialStructures\src\FinancialStructures\FinancialStructures.csproj" />
    </ItemGroup>
</Project>
